### PR TITLE
Blueprints validator

### LINKED ISSUE #33: Check blueprints well-formedness in CI
Run [Drafter](https://github.com/apiaryio/drafter-npm) in Travis CI environment to prove that API blueprints are well-formed. See https://github.com/riboseinc/ribose-api/issues/1#issuecomment-341796160 and subsequent comments for rationale and details.

### PR DESCRIPTION
**Pull request by skalee**
This is an initial version of Drafter-based validator. Comments are welcome.

1. I had troubles with compiling a C-based variant of Drafter, therefore I've decided to use Drafter.js, its Emscripten-powered JavaScript counterpart.
2. Validator reports plenty of errors for our current blueprints. Maybe it's worth to ignore some error types. Here is the output: https://gist.github.com/skalee/a66ab5953373022d1a41e32060816df1.
3. All reusable component (like https://github.com/riboseinc/ribose-api/blob/master/sections/profile/profile.apib) do not pass because they aren't meant to be complete documents. Perhaps we should skip them when validating.
4. In order to run the validator, install Node.js and do following:
```
$ npm install colors drafter.js glob
$ node validator.js
```

Fixes #33.

### CODE REVIEW

**Comment by ribose-jeffreylau** [comment]
Nice!

I think we should make it only check the final APIB output file, _i.e._ `apiary.apib`, because all other files can only be considered as inputs and thus are not representational.

The other thing is, I haven't found a way yet to specify empty strings as sample values in APIB, which is why you'd see [warnings about having no specified values](https://gist.github.com/skalee/a66ab5953373022d1a41e32060816df1#file-gistfile1-txt-L4).

**Comment by skalee** [comment]
I suppose checking `sections/*.apib` may be useful as well. Output is more useful than for the aggregated document because it tells you issue location precisely.

**Comment by skalee** [comment]
OK, got your point.

**Comment by skalee** [comment]
@ribose-jeffreylau Why not:

```markdown
+ `s`: `""` (string) - pagination synchronization string
```
or
```markdown
+ `s` (string) - pagination synchronization string
```
instead of:
```markdown
+ `s`:  (string) - pagination synchronization string
```

Both do pass in my validator.

**Comment by skalee** [comment]
@ronaldtse Might be a good idea to enable Travis for this repository.

**Comment by skalee** [comment]
Regarding the aggregated document validity, the current result is as follows:

```
Checking apiary.apib… FAIL
  warning code 5 in line 195 - ignorning unrecognized block:
    [comment]: <> (REFERENCE section)
  warning code 6 in line 2667 - no value(s) specified:
    `body`:  (string) - Body of invitation message to the invitees
  warning code 6 in line 2705 - no value(s) specified:
    `s`:  (string) - pagination synchronization string
  warning code 6 in line 2800 - no value(s) specified:
    `s`:  (string) - pagination synchronization string
  warning code 6 in line 2843 - no value(s) specified:
    `body`:  (string) - Body of invitation message to the invitees
  warning code 6 in line 2941 - no value(s) specified:
    `s`:  (string) - pagination synchronization string
  warning code 2 in line 3032 - action with method 'PUT' already defined for resource '/invitations/join_space_request/{invitation_id}':
    #### Updating pre-assigned role [PUT]
  warning code 6 in line 3067 - no value(s) specified:
    `s`:  (string) - pagination synchronization string
```

So we got three kinds of warnings.
* `warning code 6 - no value(s) specified` – as reported earlier by Jeffrey
* `warning code 2 - action with method 'PUT' already defined for resource…` – looks like a real issue to me, comes from:
```markdown
### Join Space Request [/invitations/join_space_request/{invitation_id}]
…
#### Accepting / Rejecting a.k.a Ignoring [PUT]
…
#### Updating pre-assigned role [PUT]
…
```
* `warning code 5 - ignorning unrecognized block` – no idea whether it's a true issue or a false positive

**Comment by ronaldtse** [comment]
@skalee enabled Travis. Let's merge this for now and keep the warnings to separate issues. Thanks!

**Comment by skalee** [comment]
Created #35, #36, and #37.

**Pull request merged**
